org: jona164q
app: api
service: my-express-application

provider:
name: aws
runtime: nodejs14.x
stage: dev
region: eu-central-1

functions:
app:
handler: index.handler
events:
- http: ANY /
- http: 'ANY {proxy+}'
